### ISSUE TITLE
Proposal: Loosen dispatch types

### ISSUE THREAD

**Issue by ksaldana1** [AveroLLC/types-first-ui#18]
With most of this library we were incredibly restrictive in the types we allowed to be passed around. This allowed us to leverage convenience functions and abstract away a lot of the boilerplate inherent in Redux.

One area we were particular strict was in `mapDispatchToProps`. We wanted to leverage the `app.actionCreator` function because it allowed us to pass around the discriminant for polymorphic behavior (which is consistent with how the other APIs work in this framework). This, in conjunction with the `BoundCreator` type, kept the idea of unidirectional types into our React components.

However, after working with the typesafe-routing library I have found these constraints to be too narrow. It disallows developers from creating custom/type-safe (in our case) APIs that abstract away the "redux"-ness of these APIs. For example:
```typescript
export interface TypesafeHistory<T extends Record<string, Route<any>>> {
    push<K extends keyof T>(to: K, params: RouteParams<T[K]>): Actions[ActionTypes.PUSH];
    replace<K extends keyof T>(to: K, params: RouteParams<T[K]>): Actions[ActionTypes.REPLACE];
    go(index: number): Actions[ActionTypes.GO];
    goBack(): Actions[ActionTypes.GO_BACK];
    goForward(): Actions[ActionTypes.GO_FORWARD];
}
```

I think `mapDispatch` should be a map of functions that return a type of `AllActions` (plugins + app actions). It should no longer require a unary function with the argument of the action payload. `BoundCreator` should be a generic type that receives any function and changes its return type to `void`. We can play with the types to see what type of guarantees we want from these functions/props definitions.

This will also cleanup a bit of complexity we have in our `BoundCreator` types, as they are [pretty hairy](https://github.com/AveroLLC/types-first-ui/blob/master/src/connector.ts#L39) at the moment.

**Comment by autoric** [comment]
Makes sense. I'm trying to remember what we gained from being so strict with the action creators? I think the main value was that it was easier to define the interfaces for ActionProps if they were simply derived from an action interface. 

Also, the whole point of bound creators is to take an action creator and change the contract to return void. That feels really low value. If we had our bound action creators (in the connector) return the action that was created, it would reduce some of the necessary ceremony and complicated typings.
